834 create custom action workflow to publish report
Calance-US/publish-allure-report-action pull request #1
Opened 2023-06-14 11:00 UTC by Ritik232

## Changes Applied: 
Created a script which sends data to allure tool and generated a report. Also created a action.yml workflow to create a custom action for the script.

2023-06-14 11:03 UTC, Nkashyap-calance approved these changes, later dismissed
LGTM

2023-06-15 07:52 UTC, ypmittal requested changes
code needs to pass js linting before i can review properly

From a cursory review, below improvements are needed:
- cookie parsing logic needs to be improved, preferably use some package
- error handling is incomplete. see example below. Missing return/exception to terminate the flow when API call fails.
```
                            if (report.status !== 200) {
                                core.setFailed(`Something went wrong in generating report. Status Code: ${report.status}`)
                            }
                            ```
- nesting level in the code is too high

2023-06-16 06:53 UTC, ypmittal commented on .eslintrc.json
> +        "browser": true,
should not be true

2023-06-16 06:53 UTC, ypmittal commented on action.yml
> +    description: "Path of the test results directory, relative to the test_suite_path. Defaults to test-results."
change the description

2023-06-16 06:54 UTC, ypmittal commented on action.yml
> +    description: "Username for QA tool of admin"
Username for the QA tool. Should have admin access.

2023-06-16 06:54 UTC, ypmittal commented on action.yml
> +    description: "Password for QA tool of admin"
see above comment

2023-06-16 06:59 UTC, ypmittal commented on index.js
> +const apiUrl = 'https://qa-reports.calance.work/allure-api/allure-docker-service'
take this as an input

2023-06-16 07:30 UTC, ypmittal commented on index.js
> +async function checkApiStatus () {
rename to `publishReport`

2023-06-16 07:31 UTC, ypmittal commented on index.js
> +checkApiStatus().then()
you can remove then if nothing is being done inside it

2023-06-16 10:50 UTC, ypmittal approved these changes

2023-06-16 10:51 UTC, merged